<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel Test" duration-ms="236" started-at="2017-12-22T17:59:46Z" finished-at="2017-12-22T17:59:46Z">
    <groups>
    </groups>
    <test name="Parallel_Test_2" duration-ms="235" started-at="2017-12-22T17:59:46Z" finished-at="2017-12-22T17:59:46Z">
      <class name="Automation2018.AutoShow.AppTest">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:Automation2018.AutoShow.AppTest@2d3fcdbd]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-12-22T23:29:46Z" finished-at="2017-12-22T23:29:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Automation2018.AutoShow.BaseTest.beforeTest(BaseTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="test2()[pri:0, instance:Automation2018.AutoShow.AppTest@2d3fcdbd]" name="test2" duration-ms="195" started-at="2017-12-22T23:29:46Z" finished-at="2017-12-22T23:29:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:Automation2018.AutoShow.AppTest@2d3fcdbd]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-12-22T23:29:46Z" finished-at="2017-12-22T23:29:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Automation2018.AutoShow.AppTest -->
    </test> <!-- Parallel_Test_2 -->
    <test name="Parallel_Test_1" duration-ms="236" started-at="2017-12-22T17:59:46Z" finished-at="2017-12-22T17:59:46Z">
      <class name="Automation2018.AutoShow.LearnTest">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:Automation2018.AutoShow.LearnTest@79b4d0f]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-12-22T23:29:46Z" finished-at="2017-12-22T23:29:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Automation2018.AutoShow.BaseTest.beforeTest(BaseTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="test1()[pri:0, instance:Automation2018.AutoShow.LearnTest@79b4d0f]" name="test1" duration-ms="195" started-at="2017-12-22T23:29:46Z" finished-at="2017-12-22T23:29:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:Automation2018.AutoShow.LearnTest@79b4d0f]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-12-22T23:29:46Z" finished-at="2017-12-22T23:29:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Automation2018.AutoShow.LearnTest -->
    </test> <!-- Parallel_Test_1 -->
  </suite> <!-- Parallel Test -->
</testng-results>
